### ISSUE TITLE
Pre-seeded APIs aren't working

### ISSUE THREAD

**Issue by jamietanna** [co-cddo/federated-api-model#128]
As a follow-up to #126 being deployed, we still see https://federated-api-model-spring-boot-sandbox.london.cloudapps.digital/apis render:

```json
{"api-version":"api.gov.uk/v1alpha","apis":[]}
```

**Comment by nahteb** [comment]
I think this profile should be `sandbox` instead of `staging`? https://github.com/co-cddo/federated-api-model/blob/7275c5dd4a02c84559664a8fb055f9e3af223151/examples/java/spring-boot/manifest.yml#L8

**Comment by jamietanna** [comment]
I should've checked my emails, I've spent ages thinking it's a Spring issue and debugging, but yep, that was it :joy_cat:
